server:
  port: 11001
spring:
  application:
    name: FairyQin_order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    type: com.alibaba.druid.pool.DruidDataSource
    #    url: jdbc:mysql://192.168.241.128:33061/FairyQin_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://192.168.241.128:33061/FairyQin_oms?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    password: 08170585
    username: root
mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO
  mapper-locations:
    - classpath:/mapper/**/*.xml